name: Build and Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease

      - name: Rename APK
        run: cp app/build/outputs/apk/release/app-release.apk TurnFree.apk

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TurnFree.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
